# Generated by Django 5.2.3 on 2025-07-28 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
