# Generated by Django 5.2.3 on 2025-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('paper_type', models.CharField(choices=[('CT', 'Class Test'), ('MIDSEM', 'Mid Semester'), ('ENDSEM', 'End Semester')], max_length=10)),
                ('uploaded_file', models.FileField(upload_to='papers/')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
