# Generated by Django 5.2.3 on 2025-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('1st year', 'First Year'), ('2nd year', 'Second Year'), ('3rd year', 'Third Year'), ('4th year', 'Fourth Year')], max_length=10),
        ),
    ]
